#  _____           _        _   _____
# |  __ \         | |      | | |  __ \
# | |__) |__   ___| | _____| |_| |__) |__ _ __ _ __ ___  ___
# |  ___/ _ \ / __| |/ / _ \ __|  ___/ _ \ '__| '_ ` _ \/ __|
# | |  | (_) | (__|   <  __/ |_| |  |  __/ |  | | | | | \__ \
# |_|   \___/ \___|_|\_\___|\__|_|   \___|_|  |_| |_| |_|___/
#
#
# Made by PocketEssential Copyright 2016 ©
#
# This is a public software, you cannot redistribute it a and/or modify any way
# unless otherwise given permission to do so.
#
# Author: The PocketEssential Team
# Link: https://github.com/PocketEssential
#
#|------------------------------------------------ PocketPerms ------------------------------------------------|
#| - If you made a mistake in the config, either edit it, or delete the config file, then restart your server!  |
#| - If the issue persists, report it at https://github.com/PocketEssential/PocketPerms/issues                 |
#|--------------------------------------------------------------------------------------------------------------|

# Set the date provider that  you'd like PocketPerms to use:
# Options: Yaml, MySQL, SQLite

data-provider: Yaml


MySQL:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "12345678"
  datebase: "PocketPerms"


# This option will disable /op

disable-op-command: false